services:
  db:
    image: postgres:15
    container_name: analysis_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '127.0.0.1:${POSTGRES_PORT}:5432'
    volumes:
      - analysis_db_data:/var/lib/postgresql/data

  metabase:
    image: metabase/metabase:latest
    container_name: analysis_metabase
    ports:
      - '3000:3000'
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase_db
      MB_DB_PORT: 5432
      MB_DB_USER: ${POSTGRES_USER}
      MB_DB_PASS: ${POSTGRES_PASSWORD}
      MB_DB_HOST: db
    depends_on:
      - db

volumes:
  analysis_db_data:
